extends:
  - "@sinonjs/eslint-config"

globals:
  Float32Array: false
  Float64Array: false
  Int8Array: false
  Int16Array: false
  Int32Array: false
  Map: false
  Promise: false
  Set: false
  Symbol: false
  Uint8Array: false
  Uint16Array: false
  Uint32Array: false
  Uint8ClampedArray: false
  WeakMap: false
  WeakSet: false

rules:
  quotes: off
  max-len: off
  # the sinon config is currently using prettier plugin
  # once that has been updated, this line can be removed
  # See https://github.com/sinonjs/eslint-config-sinon/blob/956db70f2e0566d0e7f8f1f093da4704cf16afb2/index.js#L288-L290
  prettier/prettier: off
